<div class="block-group box-section">
	<div class="banner_padding">
		<div class="testimo-slider">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('testimonial.phtml')->toHtml(); ?>
		</div>
	</div>
	<div class="newpr-slider">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?> 
	</div>		
	<div class="banner_padding">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_static_h2')->toHtml(); ?>	
	</div>
	<div class="container">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_bottom')->toHtml(); ?>
		<div class="blog-slider">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('sidebar/slider.phtml')->toHtml();?> 
		</div>
	</div>
</div>