<div class="block-group box-section">

	<div class="">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_static_h4')->toHtml(); ?>	
	</div>	
	<div class="newpr-slider">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?> 
	</div>		
	<div class="container">
		<div class="blog-slider">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('sidebar/slider.phtml')->toHtml();?> 
		</div>
	</div>
</div>